### PR TITLE
REWORK USER && SORTING LADDER && HISTORY:

### LINKED ISSUE #31: Add development guard
A development guard is needed in order to create some routes only if we're in a development environment.
It could allow us to remove some route in production, like POST /user, DELETE /user/:id etc..

### PR DESCRIPTION
**Pull request by AdrianWeaver**
In the context of improving code readabily and adding features to remove some burden from the front...
Added feature to get a user by username.

Reworked the user to provide useful information in a more accurate scope.

While at it, also reworked ladder and history methods for a cleaner code and sorted lists.

Also removed routes for debug now that prisma studio is in use.
This last point Fixes #31

### CODE REVIEW

**Review by riblanc — APPROVED** [review]
Thank to your work!!

**Comment by AdrianWeaver** [comment]
I added the route to get the user.
I'm using Post, so I'm a bit unsure about it. 
Please let me know if you think this makes sense.

**Comment by AdrianWeaver** [comment]
Rebased :)

**Review by riblanc — APPROVED** [review]
Nice teapot mate

**Pull request merged**
